name: Schedule Workflow3
on:
  schedule:
    - cron: '*/10 * * * *'
    - cron: '0 0 1 * *'
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher Hello World
        run: echo "Hello, world!"
